name: Deploy Backend to App Engine

on:
  push:
    branches: [main]
    paths: ["backend/**"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x backend/gradlew

      - name: Run tests
        run: |
          cd backend
          ./gradlew test

      - name: Build application
        run: |
          cd backend
          ./gradlew build -x test

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Create app.yaml with environment variables
        run: |
          cd backend
          cat > app-deploy.yaml << EOF
          runtime: java21
          instance_class: F2
          automatic_scaling:
            min_num_instances: 1
            max_num_instances: 10
          env_variables:
            SPRING_PROFILES_ACTIVE: "prod"
            DB_USERNAME: "${{ secrets.DB_USERNAME }}"
            DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
            CLOUD_SQL_CONNECTION_NAME: "${{ secrets.CLOUD_SQL_CONNECTION_NAME }}"
            CLOUD_SQL_DATABASE: "${{ secrets.CLOUD_SQL_DATABASE }}"
          EOF
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to App Engine
        run: |
          cd backend
          gcloud app deploy app-deploy.yaml --quiet
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
